/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    celebrities: Celebrity;
    looks: Look;
    items: Item;
    products: Product;
    brands: Brand;
    articles: Article;
    media: Media;
    outboundClicks: OutboundClick;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    looks: {
      items: 'items';
    };
  };
  collectionsSelect: {
    celebrities: CelebritiesSelect<false> | CelebritiesSelect<true>;
    looks: LooksSelect<false> | LooksSelect<true>;
    items: ItemsSelect<false> | ItemsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    outboundClicks: OutboundClicksSelect<false> | OutboundClicksSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    navigation: Navigation;
    footer: Footer;
    homepage: Homepage;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "celebrities".
 */
export interface Celebrity {
  id: number;
  name: string;
  /**
   * The URL segment. Auto-filled from the title; edit with care once published.
   */
  slug: string;
  category: 'film' | 'music' | 'sport' | 'creator';
  /**
   * The one-paragraph thesis under the name. What is distinctive about how this person dresses?
   */
  standfirst?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 3:4 portrait, used on cards and the hero.
   */
  portraitImage?: (number | null) | Media;
  /**
   * Wide image for the full-bleed band.
   */
  heroImage?: (number | null) | Media;
  /**
   * Pin above everything else.
   */
  featured?: boolean | null;
  /**
   * Lower numbers come first among featured items.
   */
  rank?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines.
   */
  alt: string;
  /**
   * Optional caption shown beneath the image.
   */
  caption?: string | null;
  /**
   * Photographer or agency, exactly as the licence requires it.
   */
  credit: string;
  licence: 'agency' | 'instagram-embed' | 'cc' | 'own' | 'promotional' | 'merchant-feed';
  /**
   * Which agency the licence is with.
   */
  sourceAgency?: string | null;
  /**
   * Leave empty if the licence does not expire.
   */
  licenceExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    landscape?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    logo?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "looks".
 */
export interface Look {
  id: number;
  celebrity: number | Celebrity;
  /**
   * Write a thesis, not a label. "The knit polo has quietly replaced the shirt".
   */
  title: string;
  /**
   * The URL segment. Auto-filled from the title; edit with care once published.
   */
  slug: string;
  date: string;
  location?: string | null;
  occasion?: ('airport' | 'premiere' | 'press' | 'on-set' | 'street' | 'event') | null;
  /**
   * What is actually being worn, and what gives it away.
   */
  description?: string | null;
  /**
   * First image is the lead.
   */
  photos?: (number | Media)[] | null;
  /**
   * Garments identified in this look. Add them from the Items collection.
   */
  items?: {
    docs?: (number | Item)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Pin above everything else.
   */
  featured?: boolean | null;
  /**
   * Lower numbers come first among featured items.
   */
  rank?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  /**
   * Auto-generated summary for list views.
   */
  label?: string | null;
  look: number | Look;
  category:
    | 'outerwear'
    | 'knitwear'
    | 'shirting'
    | 'tailoring'
    | 'denim'
    | 'trousers'
    | 'footwear'
    | 'eyewear'
    | 'watch'
    | 'bag'
    | 'jewellery'
    | 'other';
  /**
   * Shown to readers. Never mark something confirmed to fill a gap.
   */
  confidence: 'confirmed' | 'closest_match' | 'get_the_look' | 'open';
  /**
   * Why this call was made — "logo visible on temple". Internal only, never shown publicly, but it is the audit trail if a brand queries it.
   */
  evidenceNote?: string | null;
  /**
   * The product we link to.
   */
  product?: (number | null) | Product;
  /**
   * Cheaper stand-in, shown when the original is over $500 or out of stock.
   */
  alternativeProduct?: (number | null) | Product;
  /**
   * Display order within the look.
   */
  position?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  brand?: (number | null) | Brand;
  /**
   * One line. Cut, colour, material — what distinguishes it.
   */
  description?: string | null;
  /**
   * In minor units — 17100 for $171.00.
   */
  priceCents?: number | null;
  currency?: ('USD' | 'CAD' | 'GBP' | 'EUR') | null;
  /**
   * Derived from price and currency.
   */
  priceDisplay?: string | null;
  /**
   * The tracked merchant URL. Never rendered directly — the site links to /go/[id] and redirects.
   */
  affiliateUrl: string;
  /**
   * Where it is bought, e.g. Nordstrom.
   */
  merchant?: string | null;
  image?: (number | null) | Media;
  /**
   * Fallback image straight from the merchant feed.
   */
  imageUrl?: string | null;
  sku?: string | null;
  inStock?: boolean | null;
  /**
   * Last successful feed refresh.
   */
  priceCheckedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * The URL segment. Auto-filled from the title; edit with care once published.
   */
  slug: string;
  logo?: (number | null) | Media;
  /**
   * The brand’s own site. Rendered as a plain external link — never an affiliate one, so the page still says something useful for brands we have no programme with.
   */
  website?: string | null;
  /**
   * Year or era, shown under the brand name. Free text — “1937”, “1980s”.
   */
  founded?: string | null;
  /**
   * Shown on the brand page. Good place to rank for the brand name.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  affiliateNetwork?: ('impact' | 'cj' | 'rakuten' | 'shareasale' | 'amazon' | 'sovrn' | 'direct' | 'none') | null;
  /**
   * Percent. Informational — used to prioritise which brands to chase.
   */
  commissionRate?: number | null;
  /**
   * Pin above everything else.
   */
  featured?: boolean | null;
  /**
   * Lower numbers come first among featured items.
   */
  rank?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Picks the heading skeleton for this kind of post. Guidance only — you can write anything.
   */
  template: 'how-to' | 'listicle' | 'comparison' | 'review' | 'news' | 'generic';
  title: string;
  /**
   * Shown on cards and used as the meta description when the SEO tab is left blank. Aim for 150–160 characters.
   */
  excerpt: string;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  keywords?:
    | {
        /**
         * Matched case-insensitively, whole words only.
         */
        keyword: string;
        url: string;
        rel?: ('auto' | 'dofollow' | 'nofollow' | 'sponsored') | null;
        /**
         * Auto = dofollow for our own pages, nofollow for external. Only override to dofollow an external link when it is genuinely editorial — a paid one risks the whole site.
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * The URL segment. Auto-filled from the title; edit with care once published.
   */
  slug: string;
  publishedAt?: string | null;
  author?: string | null;
  /**
   * Surfaces this article on that celebrity page. Strong internal linking.
   */
  relatedCelebrity?: (number | null) | Celebrity;
  relatedBrand?: (number | null) | Brand;
  views?: number | null;
  /**
   * Pin above everything else.
   */
  featured?: boolean | null;
  /**
   * Lower numbers come first among featured items.
   */
  rank?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outboundClicks".
 */
export interface OutboundClick {
  id: number;
  item?: (number | null) | Item;
  product?: (number | null) | Product;
  sessionId?: string | null;
  referrer?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'articles';
          value: number | Article;
        } | null)
      | ({
          relationTo: 'celebrities';
          value: number | Celebrity;
        } | null)
      | ({
          relationTo: 'looks';
          value: number | Look;
        } | null)
      | ({
          relationTo: 'brands';
          value: number | Brand;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'celebrities';
        value: number | Celebrity;
      } | null)
    | ({
        relationTo: 'looks';
        value: number | Look;
      } | null)
    | ({
        relationTo: 'items';
        value: number | Item;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'outboundClicks';
        value: number | OutboundClick;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "celebrities_select".
 */
export interface CelebritiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  standfirst?: T;
  bio?: T;
  portraitImage?: T;
  heroImage?: T;
  featured?: T;
  rank?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "looks_select".
 */
export interface LooksSelect<T extends boolean = true> {
  celebrity?: T;
  title?: T;
  slug?: T;
  date?: T;
  location?: T;
  occasion?: T;
  description?: T;
  photos?: T;
  items?: T;
  featured?: T;
  rank?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  label?: T;
  look?: T;
  category?: T;
  confidence?: T;
  evidenceNote?: T;
  product?: T;
  alternativeProduct?: T;
  position?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  description?: T;
  priceCents?: T;
  currency?: T;
  priceDisplay?: T;
  affiliateUrl?: T;
  merchant?: T;
  image?: T;
  imageUrl?: T;
  sku?: T;
  inStock?: T;
  priceCheckedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  website?: T;
  founded?: T;
  description?: T;
  affiliateNetwork?: T;
  commissionRate?: T;
  featured?: T;
  rank?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  template?: T;
  title?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        url?: T;
        rel?: T;
        note?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  publishedAt?: T;
  author?: T;
  relatedCelebrity?: T;
  relatedBrand?: T;
  views?: T;
  featured?: T;
  rank?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  licence?: T;
  sourceAgency?: T;
  licenceExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        portrait?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        landscape?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        logo?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outboundClicks_select".
 */
export interface OutboundClicksSelect<T extends boolean = true> {
  item?: T;
  product?: T;
  sessionId?: T;
  referrer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Used in the default page title.
   */
  tagline?: string | null;
  defaultDescription: string;
  logo?: (number | null) | Media;
  /**
   * Fallback social share image, 1200×630.
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Required by the FTC and shown near the links, not only in the footer. Keep it plain.
   */
  affiliateDisclosure: string;
  nonAffiliationNotice: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Header links, in order.
   */
  items?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  blurb?: string | null;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  sections?: (HomeHeroBlock | LatestLooksBlock | CelebrityGridBlock | StandardsBlock | JournalPreviewBlock)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock".
 */
export interface HomeHeroBlock {
  enabled?: boolean | null;
  eyebrow?: string | null;
  headline: string;
  /**
   * Rendered in italic at the end of the headline.
   */
  headlineEmphasis?: string | null;
  body?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestLooksBlock".
 */
export interface LatestLooksBlock {
  enabled?: boolean | null;
  heading?: string | null;
  viewAllHref?: string | null;
  count?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'latestLooks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CelebrityGridBlock".
 */
export interface CelebrityGridBlock {
  enabled?: boolean | null;
  heading?: string | null;
  count?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'celebrityGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StandardsBlock".
 */
export interface StandardsBlock {
  enabled?: boolean | null;
  heading?: string | null;
  items?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'standards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JournalPreviewBlock".
 */
export interface JournalPreviewBlock {
  enabled?: boolean | null;
  heading?: string | null;
  viewAllHref?: string | null;
  count?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'journalPreview';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  defaultDescription?: T;
  logo?: T;
  defaultOgImage?: T;
  affiliateDisclosure?: T;
  nonAffiliationNotice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  blurb?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        hero?: T | HomeHeroBlockSelect<T>;
        latestLooks?: T | LatestLooksBlockSelect<T>;
        celebrityGrid?: T | CelebrityGridBlockSelect<T>;
        standards?: T | StandardsBlockSelect<T>;
        journalPreview?: T | JournalPreviewBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock_select".
 */
export interface HomeHeroBlockSelect<T extends boolean = true> {
  enabled?: T;
  eyebrow?: T;
  headline?: T;
  headlineEmphasis?: T;
  body?: T;
  ctaLabel?: T;
  ctaHref?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestLooksBlock_select".
 */
export interface LatestLooksBlockSelect<T extends boolean = true> {
  enabled?: T;
  heading?: T;
  viewAllHref?: T;
  count?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CelebrityGridBlock_select".
 */
export interface CelebrityGridBlockSelect<T extends boolean = true> {
  enabled?: T;
  heading?: T;
  count?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StandardsBlock_select".
 */
export interface StandardsBlockSelect<T extends boolean = true> {
  enabled?: T;
  heading?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JournalPreviewBlock_select".
 */
export interface JournalPreviewBlockSelect<T extends boolean = true> {
  enabled?: T;
  heading?: T;
  viewAllHref?: T;
  count?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'celebrities';
          value: number | Celebrity;
        } | null)
      | ({
          relationTo: 'looks';
          value: number | Look;
        } | null)
      | ({
          relationTo: 'brands';
          value: number | Brand;
        } | null)
      | ({
          relationTo: 'articles';
          value: number | Article;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShoppableProductBlock".
 */
export interface ShoppableProductBlock {
  product: number | Product;
  /**
   * Small label above the product, e.g. "The item, current version".
   */
  eyebrow?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'shoppableProduct';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock".
 */
export interface PullQuoteBlock {
  quote: string;
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pullQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlockType".
 */
export interface ImageBlockType {
  image: number | Media;
  caption?: string | null;
  width?: ('measure' | 'wide' | 'bleed') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  images: (number | Media)[];
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock".
 */
export interface EmbedBlock {
  platform: 'instagram' | 'youtube' | 'x';
  /**
   * Official post URL. Embeds are the one way to show a celebrity photo without licensing it — the platform serves it, we do not host it.
   */
  url: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  tone?: ('note' | 'get-the-look') | null;
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}